//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bartersystemoel
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string points { get; set; }
        public string city { get; set; }
    }
}
